version: '3.8'
services:
  mysql:
    image: mysql:8
    build:
      dockerfile: ./backend/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "schema_attendance"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
  admin-site:
    build:
      context: .
      dockerfile: ./admin-site/Dockerfile
    ports:
      - "3000:80"

  client-site:
    build:
      context: .
      dockerfile: ./client-site/Dockerfile
    ports:
      - "3001:80"

  # Add database container here if not hosted externally
